### ISSUE TITLE
Tool Tip

### ISSUE THREAD

**Issue by markuswindegger** [tis-innovation-park/realtimebus#16]
The tooltip is quitly uncomplet. The color of the bus icon shown in the tooltip is not the same color of the bus icon clicked on. even on the tool tips of a busstation, the color of the icon showed for the line is not the same as the color which simboliced the bus.
![bildschirmfoto vom 2015-01-07 10 29 34](https://cloud.githubusercontent.com/assets/1259844/5643383/38a28a02-9658-11e4-9774-4dbf788a1b54.png)

**Comment by bertolla** [comment]
Fixed this on master
