### ISSUE TITLE
missing osm attribution on bus.bz.it

### ISSUE THREAD

**Issue by tyrasd** [tis-innovation-park/realtimebus#20]
On [bus.bz.it](http://bus.bz.it/) there is a prominent map which is AFAICT based on OpenStreetMap data. OpenStreetMap requires an attribution whenever such a map is displayed (see http://www.openstreetmap.org/copyright). This copyright message is missing on the formerly mentioned map.

On [bus.meran.eu](http://bus.meran.eu/) the attribution is present, but almost unreadable because of some text layout fuck-up: ![selection_039](https://cloud.githubusercontent.com/assets/1927298/6199533/075e3b66-b44a-11e4-8606-95fd061d0d7e.png)

**Comment by ohnewein** [comment]
On bus.Meran.EU there have been some problems with merges of different branges. The attribution element of openlayers has to be removed, to give better visibility to the much more clear custom attribution.

On bus.bz.it and traffic.bz.it the attribution has to be added. On parking.bz.it attribution to osm is included in the map already.

**Comment by ohnewein** [comment]
Attribution on http://bus.meran.eu/ has been fixed by @bertolla

**Comment by ohnewein** [comment]
Attribution on http://bus.bz.it/ has been fixed by @bertolla

**Comment by tyrasd** [comment]
Thanks!
