### ISSUE TITLE
POIs for bike rental stations are in wrong position

### ISSUE THREAD

**Issue by ohnewein** [tis-innovation-park/realtimebus#22]
The 2 POIs for the 2 bike rental stations in Meran are not positioned in the correct place.

@bertolla, I can show you where they should be on the map, tomorrow.

**Comment by bertolla** [comment]
These POIS are those which we got from Algorab and merge every day.
There are 3 solutions:
- They fix it on their webservice
- They stop sending us these coordinates and we set it manually
- We stop merging coordinates for all stations and set it manually

**Comment by ohnewein** [comment]
I think Algorab has got the positions by us. We should verify and send them the improved positions.

**Comment by bertolla** [comment]
Bump

**Comment by ohnewein** [comment]
I can show you on the map where the exact position is. So you can give the coordinates to Algorab. Would that work?

**Comment by bertolla** [comment]
Ok, send it to me and I will try to ask the technician of Algorab.

**Comment by ohnewein** [comment]
I think the following coordinates should better match the real positions:

Punto noleggio bici Terme
46.668253, 11.159233

Punto noleggio bici Stazione
46.672904, 11.149884

**Comment by rcavaliere** [comment]
Patrick B., did you send the correct coordinates to algorab? Otherwise I will contact them.

**Comment by rcavaliere** [comment]
algorab changed the coordinates, but on the map it seems that the positions are still the old ones.
