### ISSUE TITLE
Wege: Title of hiking path should be formatted better

### ISSUE THREAD

**Issue by ohnewein** [tis-innovation-park/realtimebus#23]
The title "Tappeinerweg (Richtung Meran)" is long and line break gets inserted after the word Richtung. Would be better to have the line break before the opening bracket.

![bus-meran-eu-wege-tappeinerweg](https://cloud.githubusercontent.com/assets/414797/8944278/0d229a76-3580-11e5-829c-6e085db864fd.png)

**Comment by bertolla** [comment]
Can be done by using a <br/> tag in the input data and importing the data again. Furthermore the width of the text and it's disposition depends on the device width, which means the text will be displayed in one, two or even more lines.

**Comment by ohnewein** [comment]
Seams that it would add more problems than it would resolve. Therefore I suggest to not implement it.
