### ISSUE TITLE
typos in German walking path titles

### ISSUE THREAD

**Issue by tyrasd** [tis-innovation-park/realtimebus#25]
For example: `Gilfpromenade (aufwerts)`. Here, *aufwerts* should be spelled with an umlaut instead: *[aufwärts](http://www.duden.de/rechtschreibung/aufwaerts)*. Happens a couple of times in the dataset (and similarly also for *abwerts*/*abfwerts* which should be *abwärts*).

**Comment by tyrasd** [comment]
seems to be fixed in the meantime.

**Comment by bertolla** [comment]
Not completely, but we are working on it. Thank you for the feedback :+1:
