### ISSUE TITLE
Car sharing missing data proper visualization

### ISSUE THREAD

**Issue by rcavaliere** [tis-innovation-park/realtimebus#26]
In case we don't have fresh data from DB Rent HALAPI service, we have to visualize this status in a proper way. The choice is to colour the car sharing stations in grey and to insert in the "details window" (that the user can open when he/she clicks on the station) a proper message, e.g. "car sharing data not available yet".

**Comment by bertolla** [comment]
In my opinion it would be enough if we show the date of the last update. This way it is easier to implement, we give the information the user needs and do not have to define limits and configurations 
>e.g. how old can data be and still be seen as fresh

**Comment by bertolla** [comment]
added Timestamp under station name
