### ISSUE TITLE
Car sharing thematic menu

### ISSUE THREAD

**Issue by rcavaliere** [tis-innovation-park/realtimebus#27]
The car sharing data provider has asked to include a thematic menu as for bus and walking in the bottom right of the application. When you click on it, the user is going to have some basic information about the data provider and the offered car sharing service.

**Comment by rcavaliere** [comment]
We can modify this menu so that the user can decide to visualize only certain type of vehicles. Would this be possible?

**Comment by bertolla** [comment]
As I always say, everything is possible, but in this case its quite a drag. The positionLayer is taken from geoserver which executes a query on the db. The query  will become quite complex, but as I said it can be done.

**Comment by bertolla** [comment]
Made a first implementation which will be available in the next release
