### ISSUE TITLE
Car sharing links in the detail windows

### ISSUE THREAD

**Issue by rcavaliere** [tis-innovation-park/realtimebus#28]
When the user clicks on a car sharing station, and the correspondent detail window is opened, we should add two links, as follows:
"Are you not registered yet? Register on http://www.carsharing.bz.it/it/iscrivetevi/"
"Are you already registered and want to book a vehicle? Book it on http://booking.carsharing.bz.it"

**Comment by ohnewein** [comment]
I would suggest to redice the messages to a single one. What about the following suggestion?

"Book a car" which is a link to http://booking.carsharing.bz.it

For the registration part, this should not be done in our interface, but the carsharing should on the their booking site provide the link to get registered.

**Comment by rcavaliere** [comment]
That's fine for me. Let's do like that.
