### ISSUE TITLE
Bike sharing missing data proper visualization 

### ISSUE THREAD

**Issue by rcavaliere** [tis-innovation-park/realtimebus#31]
In case we don't have fresh data from algorab service, we have to visualize this status in a proper way. The choice is to colour the bike sharing stations in grey and to insert in the "details window" (that the user can open when he/she clicks on the station) a proper message, e.g. "bike sharing data not available yet".

**Comment by rcavaliere** [comment]
It seems that the detail window of the bike sharing stations does not visualize the associated timestamp.

**Comment by bertolla** [comment]
Won't be able to fix this until monday
