### ISSUE TITLE
E-charging station detail link

### ISSUE THREAD

**Issue by rcavaliere** [tis-innovation-park/realtimebus#34]
When the user enter in the detail window of a charging station, a link for more information about e.g. access and payment of the service must be included (similarly as for other layers). This link should be automatically given by the interface with AEW.

**Comment by rcavaliere** [comment]
I think that the tag "Payment Info" in the detail window is misleading, since the link goes to a generic page of Alperia. I would change it in "Service Info".

**Comment by bertolla** [comment]
It is how Alperia calls the link and should therefore contain exactly that information. What if they change the link in 2 Weeks. We can not run after them.

Furthermore we insisted to have exactly that information, which is the one a Enduser is interested in.
Can't we ask them to improve their data??

**Comment by rcavaliere** [comment]
Ok, you are right. Let's keep it like that.
