### ISSUE TITLE
Car sharing missing data (Campo Tures / Chiusa)

### ISSUE THREAD

**Issue by rcavaliere** [tis-innovation-park/realtimebus#37]
It seems that our system does not receive the data from the stations placed in Campo Tures / Chiusa. It could be an issue related to the bounding box API calls or a matter in the data publication management at the HALAPI side.

**Comment by bertolla** [comment]
HALAPI problem

**Comment by rcavaliere** [comment]
Stations are now visualizable but the vehicles seem not to be available, while on http://booking.carsharing.bz.it/ they are. Are the information related to the associated vehicles correctly included?

**Comment by bertolla** [comment]
Yes, they are. Just now vehicles seem to be available. This is the data we get from flinkster and if one station would not be working than all would not be working correctly.
