### ISSUE TITLE
As a SASA manger I don't want to access the website sasabus.org anymore

### ISSUE THREAD

**Issue by rcavaliere** [tis-innovation-park/realtimebus#54]
- [x] change a record of website to /dev/null :rofl: 
- [x] create opendatahub endpoint for realtimebus
- [x] point mobility.meran.eu & co to new endpoints

**Comment by bertolla** [comment]
It is mandatory to set the A Record of a top level domain like sasabus.org to an ip address. Currently I pointed it to the shutdown server where d.rampanelli worked on. Please tell me a better place to point to, to avoid to have unexpected behaviour once the ip is released or reasociated.
